theme: jekyll-theme-minimal

title: Carolina FRANCO / Structures-Specialist
email: farocdc.contacto@gmail.com
description: "Ph.D Structures & Materials | MSc. Earthquake Engineering | Civil Engineer"
#MSc Earthquake Engineering (MEEES) of the [IUSS Pavia](http://www.iusspavia.it/home)
#Civil Engineer of the Industrial University of Santander [UIS](https://www.uis.edu.co/webUIS/es/index.jsp)"

logo: Photo.jpeg
show_downloads: false


# Author settings
author: Carolina FRANCO ARIZA # add your name
author-img: Photo.jpeg # add your photo
social-github: cafariza # add your Github handle
social-linkedin: cafariza # add your Linkedin handle
social-email: cafariza@gmail.com # add your Email address
