theme: jekyll-theme-minimal

title: cafariza
email: carolina.franco@univ-eiffel.fr
description: "It's not what you achieve, it's what you overcome"
logo: Photo.jpeg
show_downloads: false


# Author settings
author: Carolina FRANCO ARIZA # add your name
author-img: Photo.jpeg # add your photo
#social-twitter: flomin_ # add your Twitter handle
social-github: cafariza # add your Github handle
social-linkedin: cafariza # add your Linkedin handle
social-email: cafariza@gmail.com # add your Email address
